CREATE TABLE rotation_songs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    exchange_id INTEGER REFERENCES rotation_exchanges(id) NOT NULL,
    title VARCHAR(200) NOT NULL,
    artist VARCHAR(200) NOT NULL,
    album VARCHAR(200) 
);