CREATE TABLE rotation_songs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    exchange_id INTEGER REFERENCES rotation_exchanges(id) NOT NULL,
    added_by INTEGER REFERENCES rotation_users(id) NOT NULL,
    date_added TIMESTAMPTZ NOT NULL DEFAULT now(),
    title VARCHAR(200) NOT NULL,
    artist VARCHAR(200) NOT NULL,
    album VARCHAR(200),
    url_link VARCHAR(200) 
);