CREATE TABLE rotation_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    song_id INTEGER REFERENCES rotation_songs(id) NOT NULL,
    exchange_id INTEGER REFERENCES rotation_exchanges(id) NOT NULL,
    created_by INTEGER REFERENCES rotation_users(id) NOT NULL,
    date_added TIMESTAMPTZ NOT NULL DEFAULT now(),
    message VARCHAR(200) NOT NULL
);